# Change these first
owner: bloohq # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Bloo App
    url: https://app.bloo.io
  - name: Bloo API
    url: https://api.bloo.io
  - name: Bloo Website
    url: https://www.bloo.io
  - name: Bloo Community
    url: https://ask.bloo.io
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bloo.io
  # baseUrl: /your-repo-name
  logoUrl: https://uploads-ssl.webflow.com/611933498aa1f623c51041de/611933673e9b073fb7b8b9b5_bloo.svg
  name: Bloo
  introTitle: "**Bloo**, the simple & affordable project management software that your team will actually use!"
  introMessage: "**Work Better, Together.** From the small stuff to the big picture, Bloo organizes work so teams are clear on what to do, why it matters, and how to get it done."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - chanlito

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
