# Change these first
owner: bloohq # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Bloo App
    url: https://app.bloo.io
  - name: Bloo API
    url: https://api.bloo.io
  - name: Bloo Website
    url: https://www.bloo.io
  - name: Bloo Community
    url: https://ask.bloo.io

status-website:
  cname: status.bloo.io
  favicon: https://app.bloo.io/favicon.ico
  logoUrl: https://uploads-ssl.webflow.com/611933498aa1f623c51041de/611933673e9b073fb7b8b9b5_bloo.svg
  themeUrl: https://status.bloo.io/bloo-theme.css
  customHeadHtml: "<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap" rel="stylesheet">"
  name: Bloo
  introTitle: "**Bloo** — Teamwork, Made Simple."
  introMessage: "The **simple** & **affordable** project management software that your team will actually use!"
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO


assignees:
  - chanlito

i18n:
  footer: "© Bloo, Inc. — Teamwork, Made Simple."
